package cdc.wallet.management.model;

import cdc.wallet.management.auditing.CreatedAuditable;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Entity class that represent transactions for all wallets in the application
 *
 */
@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "wallet_transaction")
@EqualsAndHashCode(callSuper = true)
public class WalletTransaction extends CreatedAuditable implements Serializable {

    /**
     * Serial version UID for serialization and deserialization
     */
    @Serial
    private static final long serialVersionUID = 7602873129025965641L;

    /**
     * Unique identifier of the wallet transaction which will be generated by table
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long walletTransactionId;

    /**
     * Wallet id for which this transaction belongs to
     */
    @NotNull
    @Column(name = "wallet_master_id", nullable = false)
    private Long walletMasterId;

    /**
     * Type of transaction probably CREDIT or DEBIT
     */
    @NotBlank
    @Column(name = "transaction_type", nullable = false)
    private String transactionType;

    /**
     * Amount associated with the transaction for a particular amount
     */
    @NotNull
    @Column(name = "amount", nullable = false)
    private BigDecimal amount;

    /**
     * Reason why this transaction was happened
     */
    @NotBlank
    @Column(name = "description", nullable = false)
    private String description;

    public WalletTransaction(Long walletMasterId, String transactionType, BigDecimal amount, String description) {
        this.walletMasterId = walletMasterId;
        this.transactionType = transactionType;
        this.amount = amount;
        this.description = description;
    }

}
